---
driver:
  name: vz

provisioner:
  name: dummy

platforms:
  - name: centos-6.6
    driver:
      socket: 'ssh://virtuozzo.your-domain.loc'
      additional_options:
        ["--features nfs:on", "--features nfsd:on"]
      network:
        Bridged:
          dhcp: true

suites:
  - name: default
